config/routes.rb
Rails.application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "sessions#new"

  resources :sessions

shallow do
  resources :users do
    resources :aassignments
    resources :tturn_ins
  end
end

end

app/models/aassignment.rb
class Aassignment < ActiveRecord::Base

  validates :title, :description, :date, :due, presence: true
  validate :due_date
  # validate :required_or_optional

  belongs_to :user

  def due_date
    if date >= due
      errors.add(:due_date, ", due date must be after day assigned")
    end
  end

  def retrieve_tturn_in(user)
    self.tturn_ins.find_by_user_id(user.id)
  end

  # def required?
  #   @required
  # end
  # def optional?
  #   @optional
  # end
  # def required_or_optional
  #   unless required? || optional?
  #     errors[:base] << "Required or Optional must be selected"
  #   end
  # end
end

app/models/tturn_in.rb
class TturnIn < ActiveRecord::Base
  validates :url, presence: true

  belongs_to :user


end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password, :password_confirmation
  before_save :encrypt_password
  has_many :tturn_ins

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    # I understand we don't need this but want to make sure it is understood
    else
      nil
    end
  end
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/aassignments_controller.rb
class AassignmentsController < ApplicationController
  before_action :set_aassignment, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  # GET /aassignments
  # GET /aassignments.json
  def index
    @aassignments = Aassignment.all
  end

  # GET /aassignments/1
  # GET /aassignments/1.json
  def show
    @aassignments = Aassignment.find(params[:id])
  end

  # GET /aassignments/new
  def new
    @aassignment = Aassignment.new
  end

  # GET /aassignments/1/edit
  def edit
    @aassignment = Aassignment.find(params[:id])
  end

  # POST /aassignments
  # POST /aassignments.json
  def create
    @aassignment = Aassignment.new(aassignment_params)

    respond_to do |format|
      if @aassignment.save
        format.html { redirect_to @aassignment, notice: 'Aassignment was successfully created.' }
        format.json { render :show, status: :created, location: @aassignment }
      else
        format.html { render :new }
        format.json { render json: @aassignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aassignments/1
  # PATCH/PUT /aassignments/1.json
  def update
    respond_to do |format|
      if @aassignment.update(aassignment_params)
        format.html { redirect_to @aassignment, notice: 'Aassignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @aassignment }
      else
        format.html { render :edit }
        format.json { render json: @aassignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aassignments/1
  # DELETE /aassignments/1.json
  def destroy
    @aassignment.destroy
    respond_to do |format|
      format.html { redirect_to aassignments_url, notice: 'Aassignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aassignment
      @aassignment = Aassignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aassignment_params
      params.require(:aassignment).permit(:title, :description, :date, :due)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_login
    if !session[:user_id]
      redirect_to root_path, notice: "Sign Up or login"
    end
  end

  def progress(aasignment)
    tturn_in.where(user_id: session[:user_id], exercises_id: exercise.id, completed: true).any?
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/tturn_ins_controller.rb
class TturnInsController < ApplicationController
  before_action :set_tturn_in, only: [:show, :edit, :update, :destroy]

  # GET /tturn_ins
  # GET /tturn_ins.json
  def index
    @tturn_ins = TturnIn.all
  end

  # GET /tturn_ins/1
  # GET /tturn_ins/1.json
  def show
    @tturn_in = TturnIn.find(params[:id])
  end

  # GET /tturn_ins/new
  def new
    @tturn_in = TturnIn.new
  end

  # GET /tturn_ins/1/edit
  def edit
  end

  # POST /tturn_ins
  # POST /tturn_ins.json
  def create
    @tturn_in = TturnIn.new(tturn_in_params)
    @tturn_in.user_id = current_user.id

    respond_to do |format|
      if @tturn_in.save
        format.html { redirect_to @tturn_in, notice: 'Assignment Completed' }
        format.json { render :show, status: :created, location: @tturn_in }
      else
        format.html { render :new }
        format.json { render json: @tturn_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tturn_ins/1
  # PATCH/PUT /tturn_ins/1.json
  def update
    respond_to do |format|
      if @tturn_in.update(tturn_in_params)
        format.html { redirect_to @tturn_in, notice: 'Tturn in was successfully updated.' }
        format.json { render :show, status: :ok, location: @tturn_in }
      else
        format.html { render :edit }
        format.json { render json: @tturn_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tturn_ins/1
  # DELETE /tturn_ins/1.json
  def destroy
    @tturn_in.destroy
    respond_to do |format|
      format.html { redirect_to tturn_ins_url, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_aasignment
      @aassignment = Aassignment.find(params [:exercises_id])
    end

    def set_tturn_in
      @tturn_in = TturnIn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tturn_in_params
      params.require(:tturn_in).permit(:user_id, :exercises_id, :url, :completed, :priority, :default)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to aassignments_path, :notice => "Signed up!"
    else
      render "new"
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/aassignments_helper.rb
module AassignmentsHelper

  def markdown(text)
    return sanitize Kramdown::Document.new(text).to_html
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tturn_ins_helper.rb
module TturnInsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/aassignments/_form.html.erb
<%= form_for(@aassignment) do |f| %>
  <% if @aassignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aassignment.errors.count, "error") %> prohibited this aassignment from being saved:</h2>

      <ul>
      <% @aassignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.datetime_select :due %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aassignments/edit.html.erb
<h1>Editing aassignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @aassignment %> |
<%= link_to 'Back', aassignment_path %>

app/views/aassignments/index.html.erb
<h1>Current Assignments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th width="150">Date</th>
      <th width="150">Due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aassignments.each do |aassignment| %>
      <tr>
        <td><%= aassignment.title %></td>
        <td><%= aassignment.description %></td>
        <td><%= aassignment.date %></td>
        <td><%= aassignment.due %></td>
        </td>
        <td><%= link_to 'Show', aassignment %></td>
        <td><%= link_to 'Edit', edit_aassignment_path(aassignment) %></td>
        <td><%= link_to 'Destroy', aassignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aassignment', new_user_aassignment_path %>

app/views/aassignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', aassignments_path %>

app/views/aassignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @aassignment.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= markdown @aassignment.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @aassignment.date %>
</p>

<p>
  <strong>Due:</strong>
  <%= @aassignment.due %>
</p>



<%= link_to 'Edit', edit_aassignment_path(@aassignment) %> |
<%= link_to 'Back', aassignment_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Homework Tracks</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="left">
      <li class="active" ><a href="<%= user_aassignments_path(:user_id)%>">Assignments</a></li>
      <li class="divider"></li>
      <li class="active" ><a href="<%= user_tturn_ins_path(:user_id) %>">Progress</a></li>
      <li class="has-dropdown">
    </ul>
  </section>
</nav>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <div id="user_nav">
      <% if current_user %>
        Logged in as <%= current_user.email %>.
        <%= link_to "Log out", log_out_path %>
      <% else %>
        <%= link_to "Sign up", sign_up_path %> or
        <%= link_to "log in", log_in_path %>
      <% end %>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/tturn_ins/_form.html.erb
<%= form_for @tturn_in do |f| %>
  <% if @tturn_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tturn_in.errors.count, "error") %> prohibited this tturn_in from being saved:</h2>

      <ul>
      <% @tturn_in.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @tturn_in.exercises_id.nil? %>
  <div class="field">
    <%= f.label :exercises_id %>

  </div>
  <% end %>

  <div class="field">
    <%= f.label :url, "Link" %><br>
    <%= f.text_field :url, placeholder: "Add Link Here" %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tturn_ins/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

<%= link_to 'Show', @tturn_in %> |
<%= link_to 'Back', tturn_in_path %>

app/views/tturn_ins/index.html.erb
<h1>Progress</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Assignment</th>
      <th>Url</th>
      <th>Completed</th>
      <th colspan="4">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @tturn_ins.each do |tturn_in| %>
      <tr>
        <td><%= tturn_in.user_id %></td>
        <td><%= tturn_in.exercises_id %></td>
        <td><%= tturn_in.url %></td>
        <td><%= tturn_in.completed %></td>
        <td><%= link_to 'Show', tturn_in %></td>
        <td><%= link_to 'Edit', edit_tturn_in_path(tturn_in) %></td>
        <td><%= link_to 'Destroy', tturn_in, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New', new_user_tturn_in_path %>

app/views/tturn_ins/new.html.erb
<h1>Log Assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', tturn_in_path %>

app/views/tturn_ins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @tturn_in.user_id %>
</p>

<p>
  <strong>Exercises:</strong>
  <%= @tturn_in.exercises_id %>
</p>

<p>
  <strong>Url:</strong>
  <%= @tturn_in.url %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @tturn_in.completed %>
</p>


<%= link_to 'Edit', edit_tturn_in_path(@tturn_in) %> |
<%= link_to 'Back', tturn_in_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_hash %><br>
    <%= f.text_field :password_hash %>
  </div>
  <div class="field">
    <%= f.label :password_salt %><br>
    <%= f.text_field :password_salt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password hash:</strong>
  <%= @user.password_hash %>
</p>

<p>
  <strong>Password salt:</strong>
  <%= @user.password_salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>